[features]
seeds = false
[programs.devnet]
hello_solana = "6rGiNTXnd2WnT3zSokz2SNhv9EFGc9Nc7tABqRmk3Lms"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/hulk/Documents/SETUP/Solana/testnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
